//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_BricoMarche
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikel
    {
        public Artikel()
        {
            this.Video = new HashSet<Video>();
            this.Benutzer = new HashSet<Benutzer>();
        }
    
        public int ID { get; set; }
        public string Bezeichnung { get; set; }
        public decimal Preis { get; set; }
        public bool Aktiv { get; set; }
        public string Beschreibung { get; set; }
        public byte[] Bild { get; set; }
        public int Kategorie_ID { get; set; }
    
        public virtual Kategorie Kategorie { get; set; }
        public virtual ICollection<Video> Video { get; set; }
        public virtual ICollection<Benutzer> Benutzer { get; set; }
    }
}
