//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_BricoMarche
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benutzer
    {
        public Benutzer()
        {
            this.Artikel = new HashSet<Artikel>();
            this.Video = new HashSet<Video>();
        }
    
        public int ID { get; set; }
        public string Benutzername { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public System.DateTime Geburtsdatum { get; set; }
        public byte[] Passwort { get; set; }
        public bool Aktiv { get; set; }
        public string Adresse { get; set; }
        public int Ort_ID { get; set; }
        public int Gruppe_ID { get; set; }
    
        public virtual Gruppe Gruppe { get; set; }
        public virtual Ort Ort { get; set; }
        public virtual ICollection<Artikel> Artikel { get; set; }
        public virtual ICollection<Video> Video { get; set; }
    }
}
