//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_BricoMarche
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbBricoMarcheEntities : DbContext
    {
        public dbBricoMarcheEntities()
            : base("name=dbBricoMarcheEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Artikel> Artikel { get; set; }
        public DbSet<Benutzer> Benutzer { get; set; }
        public DbSet<Gruppe> Gruppe { get; set; }
        public DbSet<Kategorie> Kategorie { get; set; }
        public DbSet<Land> Land { get; set; }
        public DbSet<Ort> Ort { get; set; }
        public DbSet<Schlagwort> Schlagwort { get; set; }
        public DbSet<Video> Video { get; set; }
    }
}
