//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_BricoMarche
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ort
    {
        public Ort()
        {
            this.Benutzer = new HashSet<Benutzer>();
        }
    
        public int ID { get; set; }
        public string Bezeichnung { get; set; }
        public string PLZ { get; set; }
        public int Land_ID { get; set; }
    
        public virtual ICollection<Benutzer> Benutzer { get; set; }
        public virtual Land Land { get; set; }
    }
}
