//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_BricoMarche
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public Video()
        {
            this.VerlinkteArtikel = new HashSet<Artikel>();
            this.GemerkteBenutzer = new HashSet<Benutzer>();
            this.VieleSchlagwoerter = new HashSet<Schlagwort>();
        }
    
        public int ID { get; set; }
        public string Bezeichnung { get; set; }
        public bool Aktiv { get; set; }
        public string Beschreibung { get; set; }
        public byte[] Bild { get; set; }
        public string Pfad { get; set; }
        public int Kategorie_ID { get; set; }
    
        public virtual Kategorie EineKategorie { get; set; }
        public virtual ICollection<Artikel> VerlinkteArtikel { get; set; }
        public virtual ICollection<Benutzer> GemerkteBenutzer { get; set; }
        public virtual ICollection<Schlagwort> VieleSchlagwoerter { get; set; }
    }
}
