//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_BricoMarche
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Benutzer_Artikel
    {
        public int Benutzer_ID { get; set; }
        public int Artikel_ID { get; set; }
    }
}
